version: '3.9'

services:
  my-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=jtWpCSmMekhsacaTsfQrEahRPSsfVPaY
      - MYSQL_DB=railway
    depends_on:
      - mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jtWpCSmMekhsacaTsfQrEahRPSsfVPaY
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    command: --innodb_force_recovery=1  # Added force recovery flag for MySQL

volumes:
  mysql_data:

networks:
  my-network:
